apiVersion: v2
name: external-dns
description: Wrapper chart for ExternalDNS
type: application
version: 0.1.0
dependencies:
  - name: external-dns
    version: "1.x.x"
    repository: https://kubernetes-sigs.github.io/external-dns
