apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner
  namespace: argocd
spec:
  project: <DEVOPS_PROJECT>
  source:
    repoURL: git@github.com:raksit31667/example-argocd-app-of-apps.git
    targetRevision: HEAD
    path: charts/gha-runner
  destination:
    server: https://kubernetes.default.svc
    namespace: <RUNNER_NAMESPACE>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
