apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: service-namespaces
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: git@github.com:raksit31667/example-argocd-app-of-apps.git
              revision: main
              directories:
                - path: kustomize/service-namespaces
          - clusters:
              selector:
                matchLabels:
                  <MICROSERVICES_CLUSTER_LABEL>: "true"
  template:
    metadata:
      name: "service-namespaces-{{name}}"
    spec:
      project: <DEVOPS_PROJECT>
      source:
        repoURL: git@github.com:raksit31667/example-argocd-app-of-apps.git
        targetRevision: HEAD
        path: kustomize/service-namespaces
      destination:
        server: "{{server}}"
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
